[package]
name = "trie-standardmap"
description = "Standard test map for profiling tries"
version = "0.15.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"

[dependencies]
keccak-hasher = { path = "../keccak-hasher", version = "0.15.2"}
tetsy-hash-db = { path = "../../tetsy-hash-db" , version = "0.15.2"}
